### ISSUE TITLE
Lock timeouts

### ISSUE THREAD

**Issue by jeteon** [texthtml/php-lock#14]
How difficult would it be to put in feature where locks timeout? This package seems perfect for a file based cache project I'm currently working on but I'm concerned about processes that go off the rails reserving a lock and then dying before it can be released. 

If however, if the automatic destruction feature works even in the case of errors I suppose it wouldn't really be as necessary.

**Comment by mathroc** [comment]
Hi!

I'm not sure it's easy to do so reliably using file lock (php-lock rely on `flock` which does not supports timeout AFAIK). however, there is a [redis driver for php-lock](https://github.com/texthtml/php-lock-redis) which provides lock with a TTL that could fit your usecase if you have a redis server at your disposal

**Comment by mathroc** [comment]
note: I should document the timeout feature in the redis driver package

**Comment by jeteon** [comment]
Thanks for the reply. Unfortunately a restrictive server is the reason I'm working on the file based cache project so I'm constrained to just PHP. Its good to know about the Redis driven lock though.

**Comment by mathroc** [comment]
actually it seems you don't need to worry about that because the lock seems to always be released when the process die.

I tried it with this file (`test.php`):

```php
<?php

include 'vendor/autoload.php';

$lock = new TH\Lock\FileLock('./lock');
$lock->acquire();

sleep(10000);
```

If I start a process with `php test.php` in a shell, I can test that a second process `php test.php` in another shell cannot acquire the lock.
however if I kill (eg: `kill -9 $pid`) I can then start a new process which will be able to acquire an exclusive lock

**Comment by jeteon** [comment]
I just confirmed that this is indeed the case for a variety of process terminating signals. I'm really happy to hear that is a behaviour of this architecture =). I can certainly use it without concerns over that now.

**Comment by mathroc** [comment]
thank you for testing too and giving feedback

**Comment by jeteon** [comment]
Just out of curiosity, do you have an idea how one would automate a test like the one we just did ad-hoc? Basically, do you know of any way to run multiple independent PHP processes for a test that also interact with one another?

**Comment by mathroc** [comment]
I guess teh workflow would be something like this:

 * start a new process (maybe proc_open or pcntl_fork) the new process should acquire the lock and wait
 * in the main process wait a bit so that the other process have time to lock (maybe the other process could print something once the lock is acquired to avoid race conditions)
 * try to acquire the lock and make sure it fails
 * kill the other process
 * try to acquire the lock and make sure it succeed

phpspec - the testing framework I'm using here - would not be suited for this. but it could be done with something like behat, phpunit or atoum
